#!/bin/bash

# parse the incoming parameters
usage="$0 [-s <device1>,<device2>,.. or all ]"

if [ "${1}" != "-s" ]; then
        echo "ERROR: Please, specify target devices. Aborting."
        echo ${usage}
        exit 1;
fi

shift 1
DEVICES=${1}

echo "Rooting devices: ${DEVICES}"

adbs -s $DEVICES root
adbs -s $DEVICES remount
adbs -s $DEVICES push Superuser.apk /system/app/
adbs -s $DEVICES shell mv /system/xbin/su /system/xbin/su.back
adbs -s $DEVICES push su /system/xbin/su
adbs -s $DEVICES shell chown root.root /system/xbin/su
adbs -s $DEVICES shell chmod 6755 /system/xbin/su
adbs -s $DEVICES reboot

echo "Devices ${DEVICES} rooted succesfully"
