#!/bin/bash

# adbs: super adb
#
# GOAL:  allow to execute adb commands in multiple devices in an easy way.
# adbs does not care about the type of adb connection (USB or TCP). Also, adbs
# replaces the annoyinig serial numbers with device names.
#
# This script requires the device.lst (file that has all the info of one
# device: serial id, name, ip).
#
# author: Guillermo A. Nunez <guillermo@cozybit.com>

# source common functions and parse options
source `dirname ${0}`/common.sh

# parse the incoming parameters
usage="$0 [ -s <device1>,<device2>,.. or all or CB10:CB15 ] <adb_commands and options>"

[ "${1}" != "-s" ] && die "${usage}"

shift 1
DEVICES=${1}
shift 1

DEVICES=`validate_devices ${DEVICES}` || die "ERROR: specified devices are not valid. Valid format: -s CB1,CB2:CB8,CB15:CB20,CB99"

# iterate through all the devices
for dev in ${DEVICES}; do
        id=`name2id ${dev}`
        #verify the device name first
        if [ -z "${id}" ]; then
                echo "ERROR: device ${dev} does not exist in device.lst. Skipping device."
        else
                adb_agnostic ${id} ${*}
        fi
done
