#!/bin/bash

# GOAL: this scripts overwrites the basic ant command, in order to build any
# android project using the development keys.
#
# It requires the build-tools project/repo, available in burning-chrome.

# Source common functions and parse options
source `dirname ${0}`/common.sh

# allow user to override configuration file in environment
[ -z ${ANT_CONF} ] && ANT_CONF=${DEVDROID}/config/ant.conf
# check for the an tool
[ -z "`which ant`" ] && die "ERROR: ant tool not installed. Please install the ant package from the repositories. Aborting."

# source the config variables
if [ -e ${ANT_CONF} ]; then
        source ${ANT_CONF}
else
        die "ERROR: config file ${ANT_CONF} does not exist. Aborting."
fi

ant -Dkey.store=${KEYSTORE_PATH} -Dkey.store.password=${KEYSTORE_PASSWD} -Dkey.alias=${KEY_ALIAS} -Dkey.alias.password=${KEY_ALIAS_PASSWD} -Dsdk.dir=${ANDROID_SDK} $*
