#!/bin/bash

# Source common functions and parse options
source `dirname ${0}`/common.sh

# parse the incoming parameters
usage="$0 [ -s <device_name> ] [ -p <package_name> ] [ -h ]"
while getopts "s:p:h" options; do
    case $options in
        s ) DEV_NAME=${OPTARG};;
        p ) PKG_NAME=${OPTARG};;
        h ) echo ${usage}
            exit 1;;
        * ) echo "Invalid option!"
	    echo ${usage}
            exit 1;;
    esac
done

[ -z "${PKG_NAME}" -a -f AndroidManifest.xml ] && PKG_NAME=`extractAttributeXML AndroidManifest.xml /manifest package`
[ -z "${PKG_NAME}" ] && die "Please, provide a package name. ${usage}."
[ -z "${DEV_NAME}" ] && die "Please, provide the name of device."

ID=`name2id ${DEV_NAME}`

adbs ${ID} shell ps &> /dev/null
[ $? -eq 1 ] && { echo ${TMP}; exit 1; }
APP_PID=`adbs ${ID} shell ps | grep ${PKG_NAME} | grep -v "remote" | awk '{print $2}'`

[ -z "${APP_PID}" ] && die "The package ${PKG_NAME} is not in the list of running process. Launch the application first (or make sure it's the right package name). Aborting."

adbs ${ID} logcat | grep -e "${APP_PID}"
