#!/bin/bash

# GOAL: easily create and configure a mesh interface in order to join
# the mesh and be able to reach the android phones.
#
# NOTE: depending on the linux distribution you are using, the wifi chipset,
# etc. you might need to install some extra packages in order to use mesh. This
# script expects you to have a machine ready to stablish plinks with the
# android devices.
#
# How to enable mesh on your machine is out of the scope of this script, but
# here you have some useful tips that might help you if you know what you are
# doing:
#
#   - Use compat-wireless-2012-04-15 (or later).
#     http://linuxwireless.org/download/compat-wireless-2.6/compat-wireless-2012-04-15.tar.bz2
#   
#   - Install a version of iw with vendor_sync option (ie: v3.4-10-g90018b6)
#     git://git.sipsolutions.net/iw.git
#
# author: Guillermo A. Nunez <guillermo@cozybit.com>

# Source common functions and parse options
source $(dirname ${0})/common.sh

# check that all the needed parameters are valid
function check_parameters () {

[ -z "${MESH_ID}" -o -z "${WIFACE}" -o -z "${CHANNEL}" ] && die "ERROR: make sure that you've configured all the mesh parameters in the main config file. Aborting."

[ -z "${PARAM}" ] && 
	die "ERROR: you need to provide an action (-a <up/down>). Aborting."
[ "${PARAM}" != "up" -a "${PARAM}" != "down" ] && 
	die "ERROR: you need to provide an valid action (-a <up/down>). Aborting."

ip link show ${WIFACE} &>/dev/null || die "ERROR: the ${WIFACE} interface does not exist. Aborting."

}

function tearup () {
	sudo iw ${WIFACE} interface add ${MESH_IFACE} type mesh || \
		 die "ERROR: problem when creating the mesh interface on ${WIFACE}. Is your machine mesh enabled? Please, read the comments within this script for more info. Aborting."
	sudo ip link set dev ${WIFACE} down &> /dev/null
	sudo iw ${MESH_IFACE} set channel ${CHANNEL} ${HT_MODE} || die "ERROR: problem when setting the channel. Aborting."
	LOCAL_IP=`mac2ip $(if2mac ${WIFACE})`
	sudo ip address add dev ${MESH_IFACE} ${LOCAL_IP}/${NETMASK} broadcast ${BCAST_IP} || \
		die "ERROR: problem when configuring the ${MESH_IFACE} interface. Aborting." 
	sudo ip link set dev ${MESH_IFACE} up || die "ERROR: problem when bringing the ${MESH_IFACE} interface up. Aborting."
	[ -n  "${TTL}" ] && sudo iw dev ${MESH_IFACE} set mesh_param mesh_ttl ${TTL}
	sudo iw ${MESH_IFACE} mesh join ${MESH_ID} vendor_sync on || die "ERROR: problem joining the mesh ${MESH_ID}. Aborting."
}

function teardown () {
	ip link show ${MESH_IFACE} &> /dev/null
	if [ $? -eq 0 ]; then
                sudo ip link set dev ${MESH_IFACE} down &> /dev/null || \
			 die "ERROR: problem when bringing down the ${MESH_IFACE} interface. Aborting."
                sudo iw dev ${MESH_IFACE} del &> /dev/null || \
			die "ERROR: problem when deleting the ${MESH_IFACE} interface. Aborting."
	fi
}

#name of the mesh iface
MESH_IFACE=mesh0
NETMASK=8
BCAST_IP=10.255.255.255
MCAST_IP=225.0.0.0
FLUSH=0

# parse the incoming parameters
usage="$0 [-a <up/down> ] [ -i <meshid> ] [ -c <channel> ] [ -f (flush) ] [ -t <ht_mode> ] [ -w <w_interface> ] [ -r <retrasnmissions/TTL> ]  [-h]"
while getopts "a:i:c:ft:w:hr:" options; do
    case $options in
	a ) PARAM=${OPTARG};;
	i ) MESH_ID=${OPTARG};;
        c ) CHANNEL=${OPTARG};;
	f ) FLUSH=1;;
        t ) HT_MODE=${OPTARG};;
	w ) WIFACE=${OPTARG};;
	r ) TTL=${OPTARG};;
        h ) echo ${usage}
            exit 1;;
        * ) echo this is the option: ${option}
	    echo ${usage}
            exit 1;;
    esac
done

#first evaluate given parameters
check_parameters

if [ ${PARAM} == "up" ]; then
	[ ${FLUSH} -eq 1 ] && teardown
	ip link show ${MESH_IFACE} &> /dev/null && die "ERROR: ${MESH_IFACE} interface already exists. Aborting."
	tearup
else
	teardown
fi
